### ISSUE TITLE
Repo is private but package is publicly available on Pypi

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-cloud-sdk-python#230]
This library is available on Pypi: https://pypi.python.org/pypi/mbed-cloud-sdk/1.2.3.0

But the repo is still private. Do we intend on making this repo public?

**Comment by davidhyman** [comment]
released now, fyi :)

**Comment by bridadan** [comment]
Hooray! 🎉 

Thanks everyone!
