### ISSUE TITLE
Consider adding mechanism for receiving the other types of notifications

### ISSUE THREAD

**Issue by kuggenhoffen** [ARMmbed/mbed-cloud-sdk-python#235]
It would be useful for user to be able to receive the registered, unregistered and registration-updated notifications as well. Consider adding some mechanism for receiving those notifications.

For example something like a `ConnectAPI.get_registrations(device_id=None)` API which would return queue object and all registration notifications would be passed into that queue. Providing a device_id would only pass registrations of that specific device to the queue (IMHO this is not that useful but might be handy in some cases). Same thing for unregistrations and registration-updates.

**Comment by davidhyman** [comment]
@kuggenhoffen please see the latest release and let us know if this resolves this issue for you?
