### ISSUE TITLE
what the MBED_CLOUD_SDK_API_KEY in readme refer to

### ISSUE THREAD

**Issue by xuzhawei** [ARMmbed/mbed-cloud-sdk-python#363]

**Comment by alexl0gan** [comment]
It's the name of the environment variable for your api key. You can put `MBED_CLOUD_SDK_API_KEY=<your api key>` in a .env file, as in the README, or add it to your environment by using the command `export MBED_CLOUD_SDK_API_KEY=<your api key>`.
